imu:
    imu_id: 8
    imu_interface_type: "serial"
    imu_interface: "/dev/ttyUSB0"
    imu_type: "HIPNUC"
    baudrate: 921600

motors:
    motor_id: 
    [1, 2, 3, 4, 5, 6,
     7, 8, 9, 10, 11, 12, 13,
     14, 15, 16, 17, 18,
     19, 20, 21, 22, 23]
    motor_interface_type: "can"
    motor_interface: ["can0", "can1", "can2", "can3"]
    motor_num: [6, 7, 5, 5]
    motor_type: "DM"
    motor_model: 
        [1, 1, 1, 1, 0, 0,
         1, 1, 1, 1, 0, 0, 1,
         0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0]
    master_id_offset: 16

robot:
    kp: 
        [100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
         100.0, 100.0, 100.0, 150.0, 40.0, 40.0, 150.0,
         40.0, 40.0, 40.0, 30.0, 20.0,
         40.0, 40.0, 40.0, 30.0, 20.0]
    kd: 
        [3.3, 3.3, 3.3, 5.0, 2.0, 2.0,
         3.3, 3.3, 3.3, 5.0, 2.0, 2.0, 5.0,
         2.0, 2.0, 2.0, 1.5, 1.0,
         2.0, 2.0, 2.0, 1.5, 1.0]
    motor_sign: 
        [1, 1, 1, 1, 1, 1,
         1, 1, -1, -1, -1, -1, 1,
         1, 1, 1, 1, 1,
         -1, 1, 1, -1, 1]
    close_chain_motor_id:
        [5, 6,
         11, 12]

